### ISSUE TITLE
Wrong address

### ISSUE THREAD

**Issue by jumpjack** [mwenge/attackofthemutantcamels#1]
https://github.com/mwenge/attackofthemutantcamels/blob/64f364de154dface94ca60d4509973647eb95fd6/src/c64/amc.asm#L192

This comment should be  "**; SYS 4096 ($1000)**" , not  "**; SYS 16384 ($4000)**" (which is reset), as properly stated in following lines.

**Comment by mwenge** [comment]
Thanks for that, fixed now!

**Comment by mwenge** [comment]
Closing

**Comment by jumpjack** [comment]
In case you want to have a look to crazy things I am making with AI applied to MutantCamels code...

https://github.com/jumpjack/ArtificialCoding/blob/main/reverse/readme.md

Claude Sonnet and some other AIs  can directly generate a correct table and a correct mermaid file (I didn't even know what a mermaid file was until yesterday...), but they can't process the whole code at once, so I asked them to write a web page to process the code: none of them was able to create a fully working code, but taking one piece here, one piece there, and fixing something, I was able to obtain a working code (maybe, didn't doublecheck accurately).

Apparently the MutantCamel algorith was much more complex than it looked while playing it! :-)
